### ISSUE TITLE
Document inserted/removed event alternatives in CanJS 6 Migration Guide

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-3-4-compat#6]
This package depends on can-dom-mutate@1 and now can-dom-mutate@2 is released. I want to either:

- Add docs on how people can replicate this package for later CanJS versions
- Upgrade this package

This package only includes [dom-mutation-events.js](https://github.com/canjs/can-3-4-compat/blob/master/dom-mutation-events.js), which is only a few lines of code. I think we could document those lines in a migration guide and call it a day. Something like:

```js
import { domEvents, domMutateDomEvents } from "can";

domEvents.addEvent(domMutateDomEvents.inserted);
domEvents.addEvent(domMutateDomEvents.removed);
```

Alternatively, we could upgrade this package. We could leave the name as-is, but it might make more sense to rename the package to something more generic (maybe can-dom-mutation-events?).

**Comment by phillipskevin** [comment]
The migration guide for CanJS 4.0, gives this as an alternative for code that cannot use `connectedCallback`. Do we need to continue updating it?

**Comment by chasenlehara** [comment]
I think it’s fine to document what people can do instead. I think we should mention that in the 6.x migration guide, so if you’re using this package, you know you need to either use `connectedCallback` or do what this package was doing for you.

**Comment by phillipskevin** [comment]
Ok, I think that makes sense.
